version: '3'
services:
  # api:
  #   image: alexsong3/rust-api-example
  #   environment:
  #     DATABASE_URL: "postgres://postgres:${POSTGRES_PASSWORD}@db:5432"
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - progresDB
  progresDB:
    image: postgres:latest
    restart: always
    # environment:
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - ./.env
    ports:
      - "6540:5432"
    volumes:
      - progresDB:/var/lib/postgresql/data

volumes:
  progresDB:
    driver: local